name: Auto Release
on:
  push:
    branches:
      - master
jobs:
  check_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add permission to auto_release scripts.
        run: chmod +x ./auto_release.sh

      - name: Gradle auto release
        run: ./auto_release.sh